# Generated by Django 2.2.6 on 2019-10-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_members',
            field=models.TextField(default=''),
        ),
    ]
