# Generated by Django 2.2.6 on 2019-10-05 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0002_auto_20191005_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='artist',
            new_name='category',
        ),
    ]
