# Generated by Django 2.2.6 on 2019-10-05 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0003_auto_20191005_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'پرسش', 'verbose_name_plural': 'پرسش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'تلاش', 'verbose_name_plural': 'تلاش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'تیم', 'verbose_name_plural': 'تیم\u200cها'},
        ),
        migrations.AddField(
            model_name='team',
            name='current_problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Problem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(1, 'قبول'), (-1, 'رد'), (-2, 'بیخیال')]),
        ),
    ]
