# Generated by Django 2.2.6 on 2019-10-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0004_auto_20191005_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='solution',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
