# Generated by Django 2.2.6 on 2019-10-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0007_auto_20191008_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.BooleanField()),
            ],
        ),
    ]
